// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrSWhqfOZnwcsYayZbU1GjPsNAQHv_BF4',
    appId: '1:243861719473:web:830d8c55741349a5ee5590',
    messagingSenderId: '243861719473',
    projectId: 'presenca-42a00',
    authDomain: 'presenca-42a00.firebaseapp.com',
    storageBucket: 'presenca-42a00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzrKhiK9lWPex9WnPMu4koVDlOJI-Z-sM',
    appId: '1:243861719473:android:0b8d41ee016203a2ee5590',
    messagingSenderId: '243861719473',
    projectId: 'presenca-42a00',
    storageBucket: 'presenca-42a00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5L-WjzVH-hmgVUlASbqj11Lkhr52Ppw',
    appId: '1:243861719473:ios:63ec4c40814c639eee5590',
    messagingSenderId: '243861719473',
    projectId: 'presenca-42a00',
    storageBucket: 'presenca-42a00.appspot.com',
    iosClientId: '243861719473-qt6emnll44sddoi8shbjmofdu9pfvj82.apps.googleusercontent.com',
    iosBundleId: 'com.example.presencaAluno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz5L-WjzVH-hmgVUlASbqj11Lkhr52Ppw',
    appId: '1:243861719473:ios:63ec4c40814c639eee5590',
    messagingSenderId: '243861719473',
    projectId: 'presenca-42a00',
    storageBucket: 'presenca-42a00.appspot.com',
    iosClientId: '243861719473-qt6emnll44sddoi8shbjmofdu9pfvj82.apps.googleusercontent.com',
    iosBundleId: 'com.example.presencaAluno',
  );
}
